# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a2d2fc32c07941f27eee07835f8d5067fc9255f838c2150d7323f0a569cfd963e3986f2eb0cd4cf0ffaa7239f90f81decf155f768f346683b49ff9799ea94b3

test:
  secret_key_base: 815c3e5c45c6612335b3d0c7646383f124aafd21d1e65f61b111c2d062487c8ed292737696ae31125068fb8d97225e4b0f252e1ce9c8c829b58517af76e81d2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
